### ISSUE TITLE
Configure bus doors and remove associated seats inside the bus for user entry/exit 

### ISSUE THREAD

**Issue by sinclairjaza** [Mindinventory/react-native-bus-seat-layout#11]
Hello, 

Thanks fo this package. 

I would like to know how to configure the bus doors (because more buses have one or two doors on the right side) and how to remove the associated seats inside the bus for user entry/exit.

Because with the current configuration, the bus has only one door next to the driver.

Example with two doors: 

<img width="288" alt="image" src="https://user-images.githubusercontent.com/39466267/233606348-8bb7c32f-4566-4318-bf46-abc6233d2c89.png">

Example with one door (this door could be in the middle of the right side or near the driver : 
<img width="288" alt="image" src="https://user-images.githubusercontent.com/39466267/233606841-a2088e65-cf71-4e5e-9d55-aff8bcce62b8.png">

Thanks in advance

**Comment by chiragramimi** [comment]
@sinclairjaza, 

Thank you for your consideration. Having the ability to set the door configuration on the left and right sides would greatly enhance the flexibility of the system. Our team will be working on this. Please stay tuned for this update.

**Comment by chiragramimi** [comment]
Doors option added now in this PR and merged : https://github.com/Mindinventory/react-native-bus-seat-layout/pull/17
